CHROMIUM: arm64/efi-stub, gcov: don't profile efi-stub
With CONFIG_GCOV_KERNEL enabled, the kernel fails to link due to
the following undefined references in efi-stub.o:

arch/arm64/kernel/built-in.o: In function `_GLOBAL__sub_I_65535_0_handle_kernel_image':
/run/media/aunali/Data/pixel/kernel-dev/kernel-chromium/arch/arm64/kernel/efi-stub.c:45: undefined reference to
`__efistub___gcov_init'
/run/media/aunali/Data/pixel/kernel-dev/kernel-chromium/arch/arm64/kernel/efi-stub.c:45:(.text.startup+0x408): relocation
truncated to fit: R_AARCH64_CALL26 against undefined symbol `__efistub___gcov_init'
arch/arm64/kernel/built-in.o: In function `__efistub_$d':
arch/arm64/kernel/vdso/vdso.o:(.data+0x6fe0): undefined reference to `__efistub___gcov_merge_add'

Excluding it from GCOV profiling resolves the linking issue.

BUG=none
TEST= Kernel compiles and boots smaug \
      >> dmesg | grep gcov
      [    0.038667] gcov: version magic: 0x3630332a

Reported-by: Aun-Ali Zaidi <admin@kodeit.net>
Tested-by: Aun-Ali Zaidi <admin@kodeit.net>
Signed-off-by: Aun-Ali Zaidi <admin@kodeit.net>