CHROMIUM: devfreq: watermark: Use div_u64() for 64-bit divide operations
Building governor_wmark_active for 32 bit targets fails with the following
link error.

ERROR: "__udivdi3" [drivers/devfreq/governor_wmark_active.ko] undefined!

In addition to using div_u64(), change current_frequency_khz to unsigned
long to avoid having to use div64_u64(). current_frequency is unsigned
long, so we can be sure that current_frequency_khz won't overflow.

BUG=chromium:583462
TEST=None (build i386:allmodconfig or i386:allyesconfig)

Change-Id: I91c580c624cd6ebb679456c88abff0c05c713a38
Fixes: d2d74c3a212a ("CHROMIUM: devfreq: Add active watermark devfreq governor")
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/329566
Reviewed-by: Olof Johansson <olofj@chromium.org>
Reviewed-by: Andrew Bresticker <abrestic@chromium.org>