CHROMIUM: mfd: cros_ec_lpc: Fix build as module
MFD_CROS_EC_LPC can be configured as module. Doing so results in the followong
build errors.

ERROR: "cros_ec_lpc_reg_destroy" [drivers/platform/chrome/cros_ec_lpc.ko] undefined!
ERROR: "cros_ec_lpc_write_bytes" [drivers/platform/chrome/cros_ec_lpc.ko] undefined!
ERROR: "cros_ec_lpc_read_bytes" [drivers/platform/chrome/cros_ec_lpc.ko] undefined!

This happens because the Makefile actually treats cros_ec_lpc.o and
cros_ec_lpc_reg.o as separate modules. The functions are defined in
cros_ec_lpc_reg.o and not exported.

Since it does not add any value to have those two files as separate
modules, define a combined module which includes both files.

BUG=chromium:583462
TEST=Build x86_64:allmodconfig

Change-Id: I1ccec2ee90fa925ea36dcba42b8f6f51da824eef
Fixes: 95faf7ae0844 ("CHROMIUM: cros_ec_lpc: Add support for mec1322 EC")
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/332033
Reviewed-by: Olof Johansson <olofj@chromium.org>