CHROMIUM: ion: Add ION_POOL_CACHE_POLICY dependency on X86
Attempts to build arm images with ION_POOL_CACHE_POLICY enabled fail
with the following build errors.

drivers/staging/android/ion/ion_priv.h:
	In function 'ion_page_pool_alloc_set_cache_policy':
drivers/staging/android/ion/ion_priv.h:440:3: error:
	implicit declaration of function 'set_memory_wc'

drivers/staging/android/ion/ion_priv.h:
	In function 'ion_page_pool_free_set_cache_policy':
drivers/staging/android/ion/ion_priv.h:449:3: error:
	implicit declaration of function 'set_memory_wb'

set_memory_wc() and set_memory_wb() are only defined on X86.

BUG=chromium:583462
TEST=None (build arm:allmodconfig)

Change-Id: Ifbc1c5fa2108d7f8ebaf78b0d0029e83b3a1aa32
Fixes: b4ae23657d08 ("ANDROID: ion: Handle the memory mapping correctly on x86")
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/328970
Reviewed-by: Olof Johansson <olofj@chromium.org>