CHROMIUM: SoC: tegra: Comment out calls to non-existent functions
drivers/soc/tegra/pm.c: In function 'tegra_suspend_enter_lp0':
drivers/soc/tegra/pm.c:341:2: error:
	implicit declaration of function 'tegra_cpu_reset_handler_save'
drivers/soc/tegra/pm.c: In function 'tegra_suspend_exit_lp0':
drivers/soc/tegra/pm.c:351:2: error:
    	implicit declaration of function 'tegra_cpu_reset_handler_restore'

Fixes: 37cf06e893cef ("CHROMIUM: soc/tegra: pm: add common LP0/SC7 suspend support")
BUG=chromium:583462
TEST=None (build)

Change-Id: Ia0aa952be52193b0cc0ec055bce8c7c4875857e0
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325492
Reviewed-by: Dylan Reid <dgreid@chromium.org>