CHROMIUM: cpuidle: Add missing dummy functions
Builds such as arm:sunxi_defconfig fail with

power/suspend.c: In function 'freeze_enter':
power/suspend.c:73:2: error:
	implicit declaration of function 'cpuidle_prepare_freeze'
power/suspend.c:83:2: error:
	implicit declaration of function 'cpuidle_complete_freeze'

Add the missing dummy functions needed if CONFIG_CPU_IDLE is not enabled.

Change-Id: Idf3a0d7bfdadcab765af23e9f91de743cdb423ab
Reported-by: Olof Johannson <olof@lixom.net>
Fixes: 699f57fe543d ("CHROMIUM: freeze: Add error reporting")
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/350582
Reviewed-by: Derek Basehore <dbasehore@chromium.org>